-- Generated by Ora2Pg, the Oracle database Schema converter, version 21.1
-- Copyright 2000-2020 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=DESKTOP-KNCPJAN;sid=XE;port=1521

SET client_encoding TO 'UTF8';

SET search_path = test_user,public;
CREATE SCHEMA IF NOT EXISTS test_user;
CREATE SEQUENCE audit_ddl_seq INCREMENT 1 MINVALUE 1 NO MAXVALUE START 41 CACHE 20;
